In [21]:
import numpy as np

## 1. DataTypes & Attributes

In [22]:
# NumPy's main datatype is the ndarray (n-dimensional)
# Names: Array or Vector
# 1-dimensional
# Shape = (1, 3)
a1 = np.array([1, 2, 3]) 
a1

array([1, 2, 3])

In [23]:
type(a1)

numpy.ndarray

In [24]:
# Names: Array or Matrix
# More than 1-dimensional
# Shape = (2, 3)
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [25]:
# Names: Array or Matrix
# More than 1-dimensional
# Shape = (2, 3, 3)
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [26]:
# To find the shape of the ndarray
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [27]:
# To find the number of dimensions in an ndarray
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [29]:
# To find the datatypes of the values in the ndarray
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [30]:
# To find the number of elements in an ndarray
a1.size, a2.size, a3.size

(3, 6, 18)

# NOTE: ndarrays are a Universal DataType

In [32]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [34]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [36]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [38]:
# Create an array and fill with 1's
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# Create an array and fill with 0's
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [43]:
range_array_2 = np.arange(0, 10, 2, dtype=float)
range_array_2

array([0., 2., 4., 6., 8.])

In [45]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 5, 0, 0, 8],
       [3, 3, 2, 1, 1],
       [9, 7, 9, 5, 5]])

In [46]:
random_array.size

15

In [47]:
random_array.shape

(3, 5)

In [49]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.68340093, 0.94362935, 0.72447706],
       [0.1556464 , 0.16820552, 0.24969416],
       [0.18672705, 0.24130868, 0.89860075],
       [0.75392097, 0.00521758, 0.99610007],
       [0.15599559, 0.09109581, 0.52028078]])

In [51]:
random_array_2.shape

(5, 3)

In [52]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.74894846, 0.83924077, 0.78192962],
       [0.52527382, 0.31612503, 0.98839157],
       [0.24831916, 0.64946695, 0.68307032],
       [0.82232417, 0.69604141, 0.4487837 ],
       [0.29863078, 0.50118086, 0.40044845]])

In [59]:
# Psuedo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing array and matrices

In [60]:
# Find unique values within an array
unique_values = np.unique(random_array_4)
unique_values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a1

array([1, 2, 3])

In [65]:
a1[0]

1

In [69]:
a1[1]

2

In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [67]:
a2[0]

array([1. , 2. , 3.3])

In [70]:
a2[1]

array([4. , 5. , 6.5])

In [68]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [63]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [72]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [73]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [74]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])